site_name: Watchful Detox
theme:
  name: material
  logo: assets/watchful_logo_v2.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Welcome: "index.md"
  - "Setup":
      - Requirements: "01_setup/setup.md"
      - "Setup: Phone": "01_setup/setup_01_install_phone.md"
      - "Setup: Watch":
          - "Install App": "01_setup/setup_02_00_install_watch.md"
          - "Enable GoogleFit": "01_setup/setup_02_01_install_watch.md"
          - "Enable Sleep Tracking": "01_setup/setup_02_02_install_watch.md"
  - "Features":
      - App Usage Tracking: "02_features/usage_tracking.md"
      - App Usage Alarms: "02_features/usage_alarms.md"
      - App Usage and Health: "02_features/usage_and_health.md"
      - Data Export: "02_features/data_export.md"
  - Disclaimer: "disclaimer.md"
  - About: "about.md"
